include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
